# Generated by Django 3.1.5 on 2021-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/', verbose_name="User's Profile Image"),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username'),
        ),
    ]
