# Generated by Django 3.1.5 on 2021-01-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210123_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hobby name')),
            ],
            options={
                'verbose_name_plural': 'Hobby',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='hobbies', to='users.Hobby'),
        ),
    ]
