# Generated by Django 3.1.5 on 2021-01-23 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Group name')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Group Description')),
                ('group_img', models.ImageField(blank=True, default=None, null=True, upload_to='chat/group/', verbose_name='Group Image')),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admins', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000, verbose_name='Group Description')),
                ('message_img', models.ImageField(blank=True, default=None, null=True, upload_to='chat/message/', verbose_name='Message Image')),
                ('group_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_from', to='chat.group')),
                ('profile_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message',
            },
        ),
    ]
