# Generated by Django 3.1.5 on 2021-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210123_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='', max_length=1000, verbose_name='text message'),
        ),
    ]
