# Generated by Django 3.1.5 on 2021-01-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210123_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='text message'),
        ),
    ]
