# Generated by Django 3.1.5 on 2021-02-15 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_message_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
